emailsettings:
  privileged_sender: "jonathan@fara.de"
  mailaddress: "fu@fara.de"
  mailuser: "fu@fara.de"
  mailpassword: "fumpuslumpus"
  imapserver: "imap.hopefully.not.office365.blargh"
  imapport: 143
  smtpserver: "smtp.hopefully.not.office365.blargh"
  smtpport: 587
  folders:
    old: "WORKED"
    cur: "WORKING"
    rej: "REJECTED"
    err: "FAILED"
  alloweddomains:
    - "onecorp.bizme"
    - "secondcorp.bizme"

hydromail:
  smtpip: "127.0.0.1"
  mailfrom: "hydromail@local.host.local"
  mailreplyto: "hydromail@extern.host.tld"
  mailsubject_base: "Regenmessdaten :: Some Where There"
  mailrecipients_to:
    - "otherone@extern.host.tld"
  mailrecipients_cc:
    - "someone@extern.othercorp.tld"
    - "somehone@extern.host.tld"


redis:
  host: "127.0.0.1"
  port: 6379

google:
  gemini_api_key: "WOBBLE-DOBBLE-DINGDONG"

anthropic:
  anthropic_api_key: "sk-ant-DOBBLE-WOBBLE-DINGDONG"

ecowitt:
  application_key: "bluppkey"
  api_key: "blargkey"
  realtime_url: "https://api.ecowitt.net/api/v3/device/real_time"
  device_info_url: "https://api.ecowitt.net/api/v3/device/info"
  mac: "de:ad:be:ef:fe:ed"

netatmo:
  username: "someusername"
  password: "somepassword"
  client_id: "someclientid"
  client_secret: "someclientsecret"
  # refresh_token: "somerefreshtoken"
  outdoormodule:
    name: "Au√üen"
    id: "01:12:34:56:22:11"
  rainmodule:
    name: "RegenModul"
    id: "01:12:34:56:33:22"


postgresql:
  host: "127.0.0.1"
  host_in_cluster: "postgresql.postgresql.svc"
  port: 5438
  port_in_cluster: 5432
  username: "postgres"
  password: "postgrespass"
  dbname: "postgres"



mqtt:
  username: "MQTT_USERNAME"
  password: "MQTT_PASS"
  host: "MQTT_HOST"
  port: 1883
  # TLS not used/implemented as of now.

mqtt_topics:
  ecowitt:
    pressure:
      topic: "ecowitt/pressure"
      subscribe: false
  netatmo:
    temperature:
      topic: "netatmo/temperature"
      subscribe: false
    rainfeed:
      topic: "netatmo/rain"
      subscribe: false
    rainfeed1h:
      topic: "netatmo/rain1h"
      subscribe: false
    rainfeed24h:
      topic: "netatmo/rain24h"
      subscribe: false
    pressurefeed:
      topic: "netatmo/pressure"
      subscribe: false
  wasserstandsmesser:
    mafeed:
      topic: "esp32/esp32_9191919191/ma"
      subscribe: false
    busvoltage:
      topic: "esp32/esp32_9191919191/busvoltage"
      subscribe: false
    wasserstandfeed:
      topic: "nodered/hydrostatics/hydrostatic0/status"
      subscribe: false

mqtt_defaultmetadata:
  # latitude, longitude, elevation for sensor/actor
  lat: 1.234567
  lon: 2.345678
  ele: 3.456

