emailsettings:
  privileged_sender: "jonathan@fara.de"
  mailaddress: "fu@fara.de"
  mailuser: "fu@fara.de"
  mailpassword: "fumpuslumpus"
  imapserver: "imap.hopefully.not.office365.blargh"
  imapport: 143
  smtpserver: "smtp.hopefully.not.office365.blargh"
  smtpport: 587
  folders:
    old: "WORKED"
    cur: "WORKING"
    rej: "REJECTED"
    err: "FAILED"
  alloweddomains:
    - "onecorp.bizme"
    - "secondcorp.bizme"

redis:
  host: "127.0.0.1"
  port: 6379

google:
  gemini_api_key: "WOBBLE-DOBBLE-DINGDONG"

anthropic:
  anthropic_api_key: "sk-ant-DOBBLE-WOBBLE-DINGDONG"

ecowitt:
  application_key: "bluppkey"
  api_key: "blargkey"
  realtime_url: "https://api.ecowitt.net/api/v3/device/real_time"
  device_info_url: "https://api.ecowitt.net/api/v3/device/info"
  mac: "de:ad:be:ef:fe:ed"

postgresql:
  host: "127.0.0.1"
  host_in_cluster: "postgresql.postgresql.svc"
  port: 5438
  port_in_cluster: 5432
  username: "postgres"
  password: "postgrespass"
  dbname: "postgres"



mqtt:
  username: "MQTT_USERNAME"
  password: "MQTT_PASS"
  host: "MQTT_HOST"
  port: 1883
  # TLS not used/implemented as of now.

mqtt_topics:
  ecowitt:
    pressure:
        topic: "ecowitt/pressure"
        subscribe: false

mqtt_defaultmetadata:
  # latitude, longitude, elevation for sensor/actor
  lat: 1.234567
  lon: 2.345678
  ele: 3.456