name: BuildAndPushMultiarch

#on:
#  push:
#    branches:
#      - "main"
#
#  pull_request:

on:
  workflow_run:
    workflows: ["mypy and pytests"]
    branches: ["main"]
    types:
      - completed

# CHECK: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
#on:
#  - workflow_dispatch
#  - push:
#      branches:
#        - 'main'
#        - 'dev'
#      tags:
#        - 'v*.*.*'
#  - pull_request:
#    branches:
#      - 'main'
#      - 'dev'


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Get the repository's code
      # NOTE: not really needed since build-push-action uses the "Git context"
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: get some runtime info
        run: |
          echo PWD: $(pwd)
          echo ENV: $(env)
          echo GH-REF: ${{ github.ref }}
          echo GH-SHA: ${{ github.sha }}
          tree

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Berlin Time
        id: berlin_time
        run: |
          BUILDTIME=$(TZ='Europe/Berlin' date +'%Y-%m-%d %H:%M:%S %Z')
          echo "buildtime=${BUILDTIME}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/aarch64
          # github.event_name ist hier dann immer "workflow_run"
          push: ${{ github.event_name != 'pull_request' }}
          tags: "xomoxcc/somestuff:latest,xomoxcc/somestuff:python-3.14-trixie"
          build-args: |
            buildtime=${{ steps.berlin_time.outputs.buildtime }}
            python_version=3.14
            debian_version=trixie
          # tags: ${{ steps.<meta_id>.outputs.tags }}
          # labels: ${{ steps.<meta_id>.outputs.labels }}

#      - name: Login to GHCR
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Login to Docker Hub
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Docker meta
#          id: <meta_id> # you'll use this in the next step
#          uses: docker/metadata-action@v3
#          with:
#            # list of Docker images to use as base name for tags
#            images: |
#              <specify the image name>
#            # Docker tags based on the following events/attributes
#            tags: |
#              type=schedule
#              type=ref,event=branch
#              type=ref,event=pr
#              type=semver,pattern={{version}}
#              type=semver,pattern={{major}}.{{minor}}
#              type=semver,pattern={{major}}
#              type=sha
